/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as productionNoLossVaultSol from "./ProductionNoLossVault.sol";
export type { productionNoLossVaultSol };
export type { MockUSDT } from "./MockUSDT";
export type { NoLossVault } from "./NoLossVault";
export type { PlayerDex } from "./PlayerDex";
export type { PlayerShares } from "./PlayerShares";
