/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAavePoolAddressesProvider,
  IAavePoolAddressesProviderInterface,
} from "../../../contracts/ProductionNoLossVault.sol/IAavePoolAddressesProvider";

const _abi = [
  {
    inputs: [],
    name: "getPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAavePoolAddressesProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IAavePoolAddressesProviderInterface {
    return new Interface(_abi) as IAavePoolAddressesProviderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAavePoolAddressesProvider {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAavePoolAddressesProvider;
  }
}
